#!/usr/bin/env bash
#
# One command to get a working local Jitsi stack.
#
# Writes a `.env` tuned for localhost, generates the four secrets, generates a
# TLS certificate whose SANs cover localhost, and prints the two values that must
# be copied into the Ameen backend's own `.env`.
#
# WHY A SEPARATE SCRIPT FROM .env.example: that file is the deployment template —
# it documents every option for a real VPS. Local development needs a specific,
# non-obvious subset (no Let's Encrypt, a non-privileged HTTPS port, and the LAN
# address rather than 127.0.0.1 for media), and getting any one of those wrong
# produces a failure that looks like something else entirely. Encoding the working
# combination beats asking a developer to derive it.
#
# Safe to re-run: it will not overwrite an existing .env unless --force is given.

set -euo pipefail
cd "$(dirname "$0")"

FORCE=0
PRINT_ONLY=0
case "${1:-}" in
  --force) FORCE=1 ;;
  # Emits ONLY the backend env block on stdout, so it can be redirected into a
  # file without the secret ever being displayed. Requires an existing .env.
  --print-backend-env) PRINT_ONLY=1 ;;
esac

if [[ $PRINT_ONLY -eq 1 ]]; then
  if [[ ! -f .env ]]; then
    echo "No .env found. Run ./setup-local.sh first." >&2
    exit 1
  fi
  port="$(grep -E '^HTTPS_PORT=' .env | cut -d= -f2-)"
  printf 'JITSI_DOMAIN=localhost\n'
  printf 'JITSI_PUBLIC_URL=https://localhost:%s\n' "${port:-8443}"
  printf 'JITSI_ROOM_PREFIX=ameen-dev\n'
  printf 'JITSI_JWT_APP_ID=%s\n' "$(grep -E '^JWT_APP_ID=' .env | cut -d= -f2-)"
  printf 'JITSI_JWT_APP_SECRET=%s\n' "$(grep -E '^JWT_APP_SECRET=' .env | cut -d= -f2-)"
  printf 'JITSI_JWT_TTL_SECONDS=3600\n'
  exit 0
fi

HTTPS_PORT="${HTTPS_PORT:-8443}"
HTTP_PORT="${HTTP_PORT:-8000}"

# The address a second device uses to reach the videobridge. 127.0.0.1 is the
# single most common local misconfiguration: the call connects, and every
# participant beyond the first gets silence and a frozen tile, because the bridge
# advertised an address that means "inside this container".
LAN_IP="$(ipconfig getifaddr en0 2>/dev/null || ipconfig getifaddr en1 2>/dev/null || hostname -I 2>/dev/null | awk '{print $1}' || true)"
if [[ -z "$LAN_IP" ]]; then
  LAN_IP="127.0.0.1"
  echo "WARNING: could not detect a LAN address; falling back to 127.0.0.1."
  echo "         A single browser on this machine will work. A second device will"
  echo "         connect but receive no media. Set DOCKER_HOST_ADDRESS by hand."
  echo
fi

if [[ -f .env && $FORCE -eq 0 ]]; then
  echo ".env already exists — leaving it alone (use --force to regenerate)."
else
  cat > .env <<ENVEOF
# Generated by setup-local.sh for LOCAL DEVELOPMENT ONLY.
# Not a deployment template — see .env.example for that.

JITSI_IMAGE_TAG=stable-9955

# Local hostname. "localhost" is deliberate: browsers treat it as a secure
# context, and the generated certificate's SANs cover it.
JITSI_DOMAIN=localhost
PUBLIC_URL=https://localhost:${HTTPS_PORT}
TZ=Asia/Riyadh

# Non-privileged ports so this runs without sudo.
HTTP_PORT=${HTTP_PORT}
HTTPS_PORT=${HTTPS_PORT}
JVB_PORT=10000

# No public DNS locally, so no ACME challenge is possible.
ENABLE_LETSENCRYPT=0
LETSENCRYPT_EMAIL=
LETSENCRYPT_USE_STAGING=0

# HTTPS stays ON. Jitsi is unusable without it - see generate-local-cert.sh.
DISABLE_HTTPS=0
ENABLE_HTTP_REDIRECT=1

# Media routing. See the note above about 127.0.0.1.
DOCKER_HOST_ADDRESS=${LAN_IP}
JVB_ADVERTISE_IPS=

# Token authentication ON even locally, so local behaviour matches production and
# the authorization path is actually exercised rather than bypassed.
ENABLE_AUTH=1
ENABLE_GUESTS=0
AUTH_TYPE=jwt
JWT_APP_ID=ameen
JWT_APP_SECRET=

JICOFO_AUTH_USER=focus
JICOFO_AUTH_PASSWORD=
JVB_AUTH_USER=jvb
JVB_AUTH_PASSWORD=

XMPP_DOMAIN=meet.jitsi
XMPP_AUTH_DOMAIN=auth.meet.jitsi
XMPP_GUEST_DOMAIN=guest.meet.jitsi
XMPP_MUC_DOMAIN=muc.meet.jitsi
XMPP_INTERNAL_MUC_DOMAIN=internal-muc.meet.jitsi
XMPP_RECORDER_DOMAIN=recorder.meet.jitsi
XMPP_SERVER=xmpp.meet.jitsi
XMPP_BOSH_URL_BASE=http://prosody:5280
JVB_BREWERY_MUC=jvbbrewery
ENVEOF
  echo "Wrote .env for localhost:${HTTPS_PORT} (media via ${LAN_IP})"
fi

echo
./generate-secrets.sh
echo
./generate-local-cert.sh localhost

APP_ID="$(grep -E '^JWT_APP_ID=' .env | cut -d= -f2-)"

# Deliberately NOT printed: JWT_APP_SECRET can mint a join token for any room, and
# stdout ends up in terminal scrollback, tmux buffers, and CI logs. The developer
# copies it from the file instead. `--print-backend-env` below emits it only when
# explicitly asked for, so piping into a file is a conscious act.
cat <<NOTE

────────────────────────────────────────────────────────────────────────────
Set these in the Ameen backend's .env (ai-ameen-migrated-backend/.env):

    JITSI_DOMAIN=localhost
    JITSI_PUBLIC_URL=https://localhost:${HTTPS_PORT}
    JITSI_ROOM_PREFIX=ameen-dev
    JITSI_JWT_APP_ID=${APP_ID}
    JITSI_JWT_APP_SECRET=<copy from JWT_APP_SECRET in ai-ameen-jitsi/.env>
    JITSI_JWT_TTL_SECONDS=3600

The secret is not printed here on purpose. Read it with:

    grep '^JWT_APP_SECRET=' ./.env

or append the whole block straight to the backend .env without it ever
appearing on screen:

    ./setup-local.sh --print-backend-env >> ../ai-ameen-migrated-backend/.env

Then:
    ./up.sh                       # start Jitsi (adds --profile transcription
                                  # automatically when ENABLE_TRANSCRIPTIONS=1)
    ./verify-transcription.sh     # confirm Jicofo actually sees a transcriber

USE ./up.sh, NOT a bare \`docker compose up -d\`. The transcription bridge
(jigasi) sits behind a compose profile, so a bare \`up\` silently leaves it
stopped — Jicofo then reports zero transcribers and every transcription
request fails "no instances available", with nothing in any log pointing at
the cause. That failure has already happened once in this deployment.

And ONCE per browser, visit https://localhost:${HTTPS_PORT} and accept the
certificate warning before opening the Live Meeting tab.
────────────────────────────────────────────────────────────────────────────
NOTE
